
["Weapon Attribute Config"]
	#Defines whether or not the attribute requirement is used on weapons
	"Weapon Attributes" = true

["Weapons Attribute Set"]
	#item ID to set (example= magistuweaponry:golden_zweihander) 
	"slot 1 ID:" = ""
	#The type of attribute needed (Allowed values. STR, RES, VIT, INT, MAG, DEX, STA, LUCK) 
	"slot 1 TYPE:" = ""
	#The subtype of a weapon, like type but a req in the beggining {reqSTR} (Epic Fight especial items = bigSTR(big weapons) and katanaDEX(fast weapons like katana, spear, etc))
	"slot 1 SUBTYPE:" = ""
	#The value of required attribute
	"slot 1 VALUE:" = 0.0
	"slot 2 ID:" = ""
	"slot 2 TYPE:" = ""
	"slot 2 SUBTYPE:" = ""
	"slot 2 VALUE:" = 0.0
	"slot 3 ID:" = ""
	"slot 3 TYPE:" = ""
	"slot 3 SUBTYPE" = ""
	"slot 3 VALUE:" = 0.0
	"slot 4 ID:" = ""
	"slot 4 TYPE:" = ""
	"slot 4 SUBTYPE" = ""
	"slot 4 VALUE:" = 0.0
	"slot 5 ID:" = ""
	"slot 5 TYPE" = ""
	"slot 5 SUBTYPE" = ""
	"slot 5 VALUE:" = 0.0
	"slot 6 ID:" = ""
	"slot 6 TYPE:" = ""
	"slot 6 SUBTYPE:" = ""
	"slot 6 VALUE:" = 0.0
	"slot 7 ID:" = ""
	"slot 7 TYPE:" = ""
	"slot 7 SUBTYPE:" = ""
	"slot 7 VALUE:" = 0.0
	"slot 8 ID:" = ""
	"slot 8 TYPE:" = ""
	"slot 8 SUBTYPE:" = ""
	"slot 8 VALUE:" = 0.0
	"slot 9 ID:" = ""
	"slot 9 TYPE:" = ""
	"slot 9 SUBTYPE:" = ""
	"slot 9 VALUE:" = 0.0
	"slot 10 ID:" = ""
	"slot 10 TYPE:" = ""
	"slot 10 SUBTYPE:" = ""
	"slot 10 VALUE:" = 0.0
	"slot 11 ID:" = ""
	"slot 11 TYPE:" = ""
	"slot 11 SUBTYPE:" = ""
	"slot 11 VALUE:" = 0.0
	"slot 12 ID:" = ""
	"slot 12 TYPE:" = ""
	"slot 12 SUBTYPE:" = ""
	"slot 12 VALUE:" = 0.0
	"slot 13 ID:" = ""
	"slot 13 TYPE:" = ""
	"slot 13 VALUE:" = 0.0
	"slot 14 ID:" = ""
	"slot 14 TYPE:" = ""
	"slot 14 SUBTYPE:" = ""
	"slot 14 VALUE:" = 0.0
	"slot 15 ID:" = ""
	"slot 15 TYPE:" = ""
	"slot 15 SUBTYPE:" = ""
	"slot 15 VALUE:" = 0.0
	"slot 16 ID:" = ""
	"slot 16 TYPE:" = ""
	"slot 16 SUBTYPE:" = ""
	"slot 16 VALUE:" = 0.0
	"slot 17 ID:" = ""
	"slot 17 TYPE:" = ""
	"slot 17 SUBTYPE:" = ""
	"slot 17 VALUE:" = 0.0
	"slot 18 ID:" = ""
	"slot 18 TYPE:" = ""
	"slot 18 SUBTYPE:" = ""
	"slot 18 VALUE:" = 0.0
	"slot 19 ID:" = ""
	"slot 19 TYPE:" = ""
	"slot 19 SUBTYPE" = ""
	"slot 19 VALUE:" = 0.0
	"slot 20 ID:" = ""
	"slot 20 TYPE:" = ""
	"slot 20 SUBTYPE:" = ""
	"slot 20 VALUE:" = 0.0
	"slot 21 ID:" = ""
	"slot 21 TYPE:" = ""
	"slot 21 SUBTYPE:" = ""
	"slot 21 VALUE:" = 0.0
	"slot 22 ID:" = ""
	"slot 22 TYPE:" = ""
	"slot 22 SUBTYPE:" = ""
	"slot 22 VALUE:" = 0.0
	"slot 23 ID:" = ""
	"slot 23 TYPE:" = ""
	"slot 23 SUBTYPE:" = ""
	"slot 23 VALUE:" = 0.0
	"slot 24 ID:" = ""
	"slot 24 TYPE:" = ""
	"slot 24 SUBTYPE:" = ""
	"slot 24 VALUE:" = 0.0
	"slot 25 ID:" = ""
	"slot 25 TYPE:" = ""
	"slot 25 SUBTYPE:" = ""
	"slot 25 VALUE:" = 0.0
	"slot 26 ID:" = ""
	"slot 26 TYPE:" = ""
	"slot 26 SUBTYPE:" = ""
	"slot 26 VALUE:" = 0.0
	"slot 27 ID:" = ""
	"slot 27 TYPE:" = ""
	"slot 27 SUBTYPE:" = ""
	"slot 27 VALUE:" = 0.0
	"slot 28 ID:" = ""
	"slot 28 TYPE:" = ""
	"slot 28 SUBTYPE:" = ""
	"slot 28 VALUE:" = 0.0
	"slot 29 ID:" = ""
	"slot 29 TYPE:" = ""
	"slot 29 SUBTYPE:" = ""
	"slot 29 VALUE:" = 0.0
	"slot 30 ID:" = ""
	"slot 30 TYPE:" = ""
	"slot 30 SUBTYPE:" = ""
	"slot 30 VALUE:" = 0.0
	"slot 31 ID:" = ""
	"slot 31 TYPE:" = ""
	"slot 31 SUBTYPE:" = ""
	"slot 31 VALUE:" = 0.0
	"slot 32 ID:" = ""
	"slot 32 TYPE:" = ""
	"slot 32 SUBTYPE:" = ""
	"slot 32 VALUE:" = 0.0
	"slot 33 ID:" = ""
	"slot 33 TYPE:" = ""
	"slot 33 SUBTYPE:" = ""
	"slot 33 VALUE:" = 0.0
	"slot 34 ID:" = ""
	"slot 34 TYPE:" = ""
	"slot 34 SUBTYPE:" = ""
	"slot 34 VALUE:" = 0.0
	"slot 35 ID:" = ""
	"slot 35 TYPE:" = ""
	"slot 35 SUBTYPE:" = ""
	"slot 35 VALUE:" = 0.0
	"slot 36 ID:" = ""
	"slot 36 TYPE:" = ""
	"slot 36 SUBTYPE:" = ""
	"slot 36 VALUE:" = 0.0
	"slot 37 ID:" = ""
	"slot 37 TYPE:" = ""
	"slot 37 SUBTYPE:" = ""
	"slot 37 VALUE:" = 0.0
	"slot 38 ID:" = ""
	"slot 38 TYPE:" = ""
	"slot 38 SUBTYPE:" = ""
	"slot 38 VALUE:" = 0.0
	"slot 39 ID:" = ""
	"slot 39 TYPE:" = ""
	"slot 39 SUBTYPE:" = ""
	"slot 39 VALUE:" = 0.0
	"slot 40 ID:" = ""
	"slot 40 TYPE:" = ""
	"slot 40 SUBTYPE: " = ""
	"slot 40 VALUE:" = 0.0
	"slot 41 ID:" = ""
	"slot 41 TYPE:" = ""
	"slot 41 SUBTYPE:" = ""
	"slot 41 VALUE:" = 0.0
	"slot 42 ID:" = ""
	"slot 42 TYPE:" = ""
	"slot 42 SUBTYPE:" = ""
	"slot 42 VALUE:" = 0.0
	"slot 43 ID:" = ""
	"slot 43 TYPE:" = ""
	"slot 43 SUBTYPE:" = ""
	"slot 43 VALUE:" = 0.0
	"slot 44 ID:" = ""
	"slot 44 TYPE:" = ""
	"slot 44 SUBTYPE:" = ""
	"slot 44 VALUE:" = 0.0
	"slot 45 ID:" = ""
	"slot 45 TYPE:" = ""
	"slot 45 SUBTYPE:" = ""
	"slot 45 VALUE" = 0.0
	"slot 46 ID:" = ""
	"slot 46 TYPE:" = ""
	"slot 46 SUBTYPE:" = ""
	"slot 46 VALUE:" = 0.0
	"slot 48 ID:" = ""
	"slot 48 TYPE:" = ""
	"slot 48 SUBTYPE:" = ""
	"slot 48 VALUE:" = 0.0
	"slot 49 ID:" = ""
	"slot 49 TYPE:" = ""
	"slot 49 SUBTYPE:" = ""
	"slot 49 VALUE:" = 0.0
	"slot 50 ID:" = ""
	"slot 50 TYPE:" = ""
	"slot 50 SUBTYPE" = ""
	"slot 50 VALUE:" = 0.0
	"slot 51 ID:" = ""
	"slot 51 TYPE:" = ""
	"slot 51 SUBTYPE:" = ""
	"slot 51 VALUE:" = 0.0
	"slot 52 ID:" = ""
	"slot 52 TYPE:" = ""
	"slot 52 SUBTYPE:" = ""
	"slot 52 VALUE:" = 0.0
	"slot 53 ID:" = ""
	"slot 53 TYPE:" = ""
	"slot 53 SUBTYPE:" = ""
	"slot 53 VALUE:" = 0.0
	"slot 54 ID:" = ""
	"slot 54 TYPE:" = ""
	"slot 54 SUBTYPE:" = ""
	"slot 54 VALUE:" = 0.0
	"slot 55 ID:" = ""
	"slot 55 TYPE:" = ""
	"slot 55 SUBTYPE:" = ""
	"slot 55 VALUE:" = 0.0
	"slot 56 ID:" = ""
	"slot 56 TYPE:" = ""
	"slot 56 SUBTYPE:" = ""
	"slot 56 VALUE:" = 0.0
	"slot 57 ID:" = ""
	"slot 57 TYPE:" = ""
	"slot 57 SUBTYPE:" = ""
	"slot 57 VALUE:" = 0.0
	"slot 58 ID:" = ""
	"slot 58 TYPE:" = ""
	"slot 58 SUBTYPE:" = ""
	"slot 58 VALUE:" = 0.0
	"slot 59 ID:" = ""
	"slot 59 TYPE:" = ""
	"slot 59 SUBTYPE:" = ""
	"slot 59 VALUE:" = 0.0
	"slot 60 ID:" = ""
	"slot 60 TYPE:" = ""
	"slot 60 SUBTYPE:" = ""
	"slot 60 VALUE:" = 0.0
	"slot 61 ID:" = ""
	"slot 61 TYPE:" = ""
	"slot 61 SUBTYPE:" = ""
	"slot 61 VALUE:" = 0.0
	"slot 62 ID:" = ""
	"slot 62 TYPE:" = ""
	"slot 62 SUBTYPE:" = ""
	"slot 62 VALUE:" = 0.0
	"slot 63 ID:" = ""
	"slot 63 TYPE:" = ""
	"slot 63 SUBTYPE:" = ""
	"slot 63 VALUE:" = 0.0
	"slot 64 ID:" = ""
	"slot 64 TYPE:" = ""
	"slot 64 SUBTYPE:" = ""
	"slot 64 VALUE:" = 0.0
	"slot 65 and up soon!! Wuuu" = ""
	"slot 47 ID:" = ""
	"slot 47 TYPE:" = ""
	"slot 47 SUBTYPE:" = ""
	"slot 47 VALUE:" = 0.0
	"slot 65 ID:" = ""
	"slot 65 TYPE:" = ""
	"slot 65 SUBTYPE:" = ""
	"slot 65 VALUE:" = 0.0
	"slot 66 ID:" = ""
	"slot 66 TYPE:" = ""
	"slot 66 SUBTYPE:" = ""
	"slot 66 VALUE:" = 0.0
	"slot 67 ID:" = ""
	"slot 67 TYPE:" = ""
	"slot 67 SUBTYPE:" = ""
	"slot 67 VALUE:" = 0.0
	"slot 68 ID: " = ""
	"slot 68 TYPE:" = ""
	"slot 68 SUBTYPE:" = ""
	"slot 68 VALUE:" = 0.0
	"slot 69 ID:" = ""
	"slot 69 TYPE:" = ""
	"slot 69 SUBTYPE:" = ""
	"slot 69 VALUE:" = 0.0
	"slot 70 ID:" = ""
	"slot 70 TYPE:" = ""
	"slot 70 SUBTYPE:" = ""
	"slot 70 VALUE:" = 0.0
	"slot 71 ID:" = ""
	"slot 71 TYPE:" = ""
	"slot 71 SUBTYPE:" = ""
	"slot 71 VALUE:" = 0.0
	"slot 72 ID:" = ""
	"slot 72 TYPE:" = ""
	"slot 72 SUBTYPE:" = ""
	"slot 72 VALUE:" = 0.0
	"slot 73 ID:" = ""
	"slot 73 TYPE:" = ""
	"slot 73 SUBTYPE:" = ""
	"slot 73 VALUE:" = 0.0
	"slot 74 ID:" = ""
	"slot 74 TYPE:" = ""
	"slot 74 SUBTYPE:" = ""
	"slot 74 VALUE:" = 0.0
	"slot 75 ID:" = ""
	"slot 75 SUBTYPE:" = ""
	"slot 76 ID:" = ""
	"slot 76 SUBTYPE:" = ""
	"slot 76 VALUE:" = 0.0
	"slot 77 ID:" = ""
	"slot 77 TYPE:" = ""
	"slot 77 SUBTYPE:" = ""
	"slot 77 VALUE:" = 0.0
	"slot 78 ID:" = ""
	"slot 78 TYPE:" = ""
	"slot 78 SUBTYPE:" = ""
	"slot 78 VALUE:" = 0.0
	"slot 79 ID:" = ""
	"slot 79 TYPE:" = ""
	"slot 79 SUBTYPE:" = ""
	"slot 79 VALUE:" = 0.0
	"slot 80 ID:" = ""
	"slot 80 TYPE:" = ""
	"slot 80 SUBTYPE:" = ""
	"slot 80 VALUE:" = 0.0
	"slot 81 ID:" = ""
	"slot 81 TYPE:" = ""
	"slot 81 SUBTYPE:" = ""
	"slot 81 VALUE:" = 0.0
	"slot 82 ID:" = ""
	"slot 82 TYPE:" = ""
	"slot 82 SUBTYPE:" = ""
	"slot 82 VALUE:" = 0.0
	"slot 75 VALUE:" = 0.0
	"slot 75 TYPE:" = ""
	"slot 76 TYPE:" = ""

